github action fixes 1

diff --git a/.github/workflows/pr-quality-workflow.yml b/.github/workflows/pr-quality-workflow.yml
--- a/.github/workflows/pr-quality-workflow.yml
+++ b/.github/workflows/pr-quality-workflow.yml
@@ -1,20 +1,28 @@
 name: CI Workflow
 
 on:
+  push:
+    branches: [main]
   pull_request:
     branches: [main]
 
 jobs:
-  build-and-test:
-    name: Build and Test
+  ci:
+    name: Build, Lint, and Test
     runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
+    strategy:
+      matrix:
+        node-version: [20.x] # Using Node.js version 20.x
 
-      - name: Setup Node.js
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+
+      - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: "14"
+          node-version: ${{ matrix.node-version }}
+          cache: "npm"
 
       - name: Install Dependencies
         run: npm install
@@ -22,7 +30,7 @@ jobs:
       - name: Run Linter
         run: npm run lint
 
-      - name: Run Tests
+      - name: Run Unit Tests
         run: npm test
 
   code-quality-check:
@@ -46,4 +54,29 @@ jobs:
           if [[ ! "${{ github.head_ref }}" =~ ^(feature|bugfix|hotfix)/ ]]; then
             echo "Branch naming convention not followed. Branch name must start with 'feature/', 'bugfix/', or 'hotfix/'."
             exit 1
+          fi
+
+  enforce-commit-message:
+    name: Enforce Commit Message Format
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Commit Message
+        run: |
+          if [[ ! "$(git log --format=%s --no-merges -1)" =~ ^[A-Z].* ]]; then
+            echo "Commit message format not followed. The first letter of the commit message must be capitalized."
+            exit 1
+          fi
+  branch-protection:
+    name: Branch Protection
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Branch Protection
+        run: |
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            if [[ "${{ github.event.action }}" == "opened" ]]; then
+              if [[ "${{ github.base_ref }}" == "main" ]]; then
+                echo "Branch protection enforced. You cannot push directly to the main branch."
+                exit 1
+              fi
+            fi
           fi
